In [6]:
import numpy as np

N, D = 5, 128
X = np.random.randn(N, D)

# 1) Gram matrix
G = X @ X.T  # (N, N)

# 2) Cosine similarity
norms = np.linalg.norm(X, axis=1, keepdims=True)
S_cos = (X @ X.T) / (norms @ norms.T + 1e-12)

print("Gram matrix:\n", G)
print("Cosine similarity:\n", S_cos)


Gram matrix:
 [[118.07871053   7.450451    -9.4358687    1.59109352   2.30481905]
 [  7.450451   120.02737482  20.53075358  -1.52140255  -2.37076287]
 [ -9.4358687   20.53075358 110.48526459  -2.85510363  -6.79651938]
 [  1.59109352  -1.52140255  -2.85510363  83.26061688  -1.72913585]
 [  2.30481905  -2.37076287  -6.79651938  -1.72913585 116.5845992 ]]
Cosine similarity:
 [[ 1.          0.06258303 -0.08261215  0.01604686  0.01964402]
 [ 0.06258303  1.          0.17828408 -0.01521893 -0.02004137]
 [-0.08261215  0.17828408  1.         -0.02976802 -0.05988441]
 [ 0.01604686 -0.01521893 -0.02976802  1.         -0.01755047]
 [ 0.01964402 -0.02004137 -0.05988441 -0.01755047  1.        ]]


In [7]:
norms

array([[10.86640283],
       [10.95570056],
       [10.51119711],
       [ 9.12472558],
       [10.79743484]])

In [4]:
import torch
import torch.nn.functional as F

# Suppose you already have a batch of embeddings from a model
# shape: (N, D) = (num_items, embedding_dim)
# e.g., random demo data:
N, D = 5, 128
X = F.normalize(torch.randn(N, D), p=2, dim=1)  # often embeddings are L2-normalized

# 1) Gram matrix (inner products): G_ij = <x_i, x_j>
G = X @ X.t()            # shape: (N, N)

# 2) Cosine-similarity matrix: with L2-normalized rows, Gram == cosine
# If X wasn't normalized, you can do:
X_raw = torch.randn(N, D)
X_unit = F.normalize(X_raw, p=2, dim=1)
S_cos = X_unit @ X_unit.t()

# 3) If you want Euclidean distances too (not a Gram matrix, but common for similarity):
D_euc = torch.cdist(X, X, p=2)  # shape: (N, N)

print("Gram matrix:\n", G)
print("Cosine similarity:\n", S_cos)
print("Euclidean distances:\n", D_euc)


Gram matrix:
 tensor([[ 1.0000,  0.0469,  0.1501, -0.0599, -0.0170],
        [ 0.0469,  1.0000, -0.1736, -0.1733,  0.1302],
        [ 0.1501, -0.1736,  1.0000, -0.0074,  0.0118],
        [-0.0599, -0.1733, -0.0074,  1.0000,  0.0190],
        [-0.0170,  0.1302,  0.0118,  0.0190,  1.0000]])
Cosine similarity:
 tensor([[ 1.0000,  0.0778, -0.0053, -0.0173,  0.0758],
        [ 0.0778,  1.0000, -0.1807, -0.0248, -0.1515],
        [-0.0053, -0.1807,  1.0000, -0.0094,  0.0923],
        [-0.0173, -0.0248, -0.0094,  1.0000,  0.0309],
        [ 0.0758, -0.1515,  0.0923,  0.0309,  1.0000]])
Euclidean distances:
 tensor([[0.0000, 1.3807, 1.3037, 1.4560, 1.4262],
        [1.3807, 0.0000, 1.5321, 1.5318, 1.3190],
        [1.3037, 1.5321, 0.0000, 1.4195, 1.4059],
        [1.4560, 1.5318, 1.4195, 0.0000, 1.4007],
        [1.4262, 1.3190, 1.4059, 1.4007, 0.0000]])


In [5]:
norms

array([[10.73627772],
       [12.11478442],
       [12.8532105 ],
       [12.26659525],
       [11.73652804]])